name: Build and Push Versioned Images to ECR and Deploy to ECS

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  REPO: ${{ secrets.ECR_REPOSITORY }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
  POSTGRES_PWD: ${{ secrets.POSTGRES_PWD }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  TASK_DEFINITION_FAMILY: ${{ secrets.TASK_DEFINITION_FAMILY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get latest version and bump
        id: version
        run: |
          set -e

          REPO_NAME=$(echo "${REPO}" | cut -d'/' -f2)

          echo "Checking existing tags in ECR repo: $REPO_NAME"

          TAGS=$(aws ecr describe-images \
            --repository-name "$REPO_NAME" \
            --query 'imageDetails[].imageTags[]' \
            --output text 2>/dev/null || true)

          # Filter semantic version tags like v1.2.3
          LATEST=$(echo "$TAGS" | tr '\t' '\n' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)

          if [ -z "$LATEST" ]; then
            echo "No version found. Starting at v1.0.0"
            NEXT="v1.0.0"
          else
            echo "Latest version: $LATEST"

            VERSION=${LATEST#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

            PATCH=$((PATCH + 1))
            NEXT="v${MAJOR}.${MINOR}.${PATCH}"
          fi

          echo "Next version: $NEXT"
          echo "VERSION=$NEXT" >> $GITHUB_ENV
          echo "version=$NEXT" >> $GITHUB_OUTPUT

      - name: Build vote image
        run: |
          docker build ./docker/vote \
            -t "${REPO}:vote-${VERSION}" \
            -t "${REPO}:vote-latest" \
            --build-arg REDIS_HOST="${REDIS_HOST}"

      - name: Build result image
        run: |
          docker build ./docker/results \
            -t "${REPO}:result-${VERSION}" \
            -t "${REPO}:result-latest"

      - name: Build worker image
        run: |
          docker build ./docker/worker \
            -t "${REPO}:worker-${VERSION}" \
            -t "${REPO}:worker-latest" \
            --build-arg POSTGRES_HOST="${POSTGRES_HOST}" \
            --build-arg POSTGRES_USERNAME="${POSTGRES_USERNAME}" \
            --build-arg POSTGRES_PWD="${POSTGRES_PWD}" \
            --build-arg REDIS_HOST="${REDIS_HOST}"

      - name: Push images to ECR
        run: |
          docker push "${REPO}:vote-${VERSION}"
          docker push "${REPO}:vote-latest"

          docker push "${REPO}:result-${VERSION}"
          docker push "${REPO}:result-latest"

          docker push "${REPO}:worker-${VERSION}"
          docker push "${REPO}:worker-latest"